In [1]:
import numpy as np
%matplotlib inline

# Matrix Review

Take the matricies:

$\bf{A} =
\begin{pmatrix}
2 & 4 & -7\\
3 & -3 & 0\\
1 & 7 & 5
\end{pmatrix},\;\;
\bf{B} =
\begin{pmatrix}
2 & 4\\
3 & -3\\
1 & 7
\end{pmatrix}, \;\;
\bf{C} =
\begin{pmatrix}
-1 & 1\\
1 & -1
\end{pmatrix}, \;\;
\bf{D} = 
\begin{pmatrix}
2 & 0\\
-3 & 6
\end{pmatrix}
$ 

Define the matricies as numpy arrays

In [9]:
A=np.array([[2, 4, -7],
            [3, -3, 0],
            [1, 7, 5]])
B=np.array([[2, 4],
            [3, -3],
            [1, 7]])
C=np.array([[-1, 1],
            [1, -1]])
D=np.array([[2, 0],
            [-3, 6]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Matrix C:\n", C)
print("Matrix D:\n", D)

Matrix A:
 [[ 2  4 -7]
 [ 3 -3  0]
 [ 1  7  5]]
Matrix B:
 [[ 2  4]
 [ 3 -3]
 [ 1  7]]
Matrix C:
 [[-1  1]
 [ 1 -1]]
Matrix D:
 [[ 2  0]
 [-3  6]]


1. Multiply $\bf{A}$ by 2.5 

In [11]:
Product_A=A*2.5
print("A*2.5=",Product_A)

A*2.5= [[  5.   10.  -17.5]
 [  7.5  -7.5   0. ]
 [  2.5  17.5  12.5]]


2. Evaluate the product of $\bf{C}\cdot\bf{A}$ 

Did you get an error? Do you know why? (Hint: look at the dimensions of the matrix)
- Got an error. the matrices are 2x2 and 3x3, so can't multiply need number of rows to match columns of other 

In [15]:
Product_C_A=C*A
#np.dot(C,A)

ValueError: shapes (2,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

3. Evaluate the product of $\bf{C}\cdot\bf{D}$ and then $\bf{D}\cdot\bf{C}$. Do you get the same results? 
- different answers CD != DC

In [17]:
Product_C_D=C*D
Product_D_C=D*C
print("C*D=",Product_C_D)
print("D*C=",Product_D_C)

C*D= [[-2  0]
 [-3 -6]]
D*C= [[-2  0]
 [-3 -6]]


4. Find the transpose of $\bf{B}$

In [21]:
B_transpose=B.T
print(B_transpose)

[[ 2  3  1]
 [ 4 -3  7]]


5. Add $\bf{C} + \bf{D}$

In [19]:
Sum_C_D=C+D
print("C+D=",Sum_C_D)

C+D= [[ 1  1]
 [-2  5]]


6. Compute the determinate of $\bf{C}$

In [27]:
determinate_C=np.linalg.det(C)
print("The determinate of C =", determinate_C)

The determinate of C = 0.0


7. Compute the determinate of $\bf{A}$

In [29]:
determinate_A=np.linalg.det(A)
print("The determinate of A =", determinate_A)

The determinate of A = -257.9999999999998
